name: CI

on:
  workflow_dispatch:

env:
  TZ: 'Asia/Tokyo'

jobs:
  version:
    runs-on: linux-latest
    steps:
      - uses: actions/checkout@v3
      - run: .github/workflows/scripts/auto-update-version.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto update MARKETING_VERSION
          branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
